Readme update
w3c/rdf-star pull request #152
Opened 2021-04-07 11:38 UTC by pchampin

README.md now simply points to the homepage.

The implementation list has been converted to HTML, and is now pointed to by the homepage.

Adresses part of #150

2021-04-07 12:26 UTC, afs commented
Are there two purposes here now?

The original purpose was "systems have been adding extensions".

We now have adoption of "RDF-star" in the EARL reports

This could be expressed either as a extra column linking to received reports, or two tables with text explaining.

2021-04-07 16:00 UTC, pchampin commented
> We now have adoption of "RDF-star" in the EARL reports

true! :)

I propose to replace the "source" link by "implementation report" for those implementation that have one.

2021-04-07 17:03 UTC, gkellogg approved these changes

2021-04-08 16:51 UTC, TallTed commented
The new unordered list provides less information, and is harder to digest, than the old table. I suggest putting the info back into a table. It may be appropriate to adjust the columns to match the evolved/evolving spec, eliminating display/mention of PG and SA modes, and instead talking about the notations and support (or lack thereof) for "unasserted embedded triples" and the like...

2021-04-09 07:49 UTC, pchampin commented
@TallTed that better?

2021-04-09 22:05 UTC, gkellogg commented on implementations.html
> +
```suggestion
        <p>For the list of submitted implementation reports see <a href="https://w3c.github.io/rdf-star/reports/">RDF-star Processor Conformance</a>.</p>

```

2021-04-11 10:04 UTC, afs requested changes

2021-04-11 10:04 UTC, afs commented on implementations.html
> +          <tr><td>Jena
```suggestion
          <tr><td>Apache Jena
```

2021-04-11 10:04 UTC, afs commented on implementations.html
> +          <tr><td>rdf4j
```suggestion
          <tr><td>Eclipse rdf4j
```

2021-04-13 15:09 UTC, merged