add section on RDF-star vocabulary
w3c/rdf-star pull request #176
Opened 2021-06-02 10:48 UTC by pchampin

2021-06-02 10:49 UTC, pchampin commented
currently, the section only contains references to the relevant issues, namely #102, #164, #169 .

2021-06-02 14:16 UTC, TallTed requested changes

2021-06-02 14:16 UTC, TallTed commented on cg-spec/editors_draft.html
> +    <p>This section will eventually describe a number of IRIs that may be useful when using RDF-star. At the moment, it contains links to the Github issues were such terms have been discussed.</p>
```suggestion
    <p>This section will eventually describe a number of IRIs that may be useful when using RDF-star. At the moment, it contains links to the Github issues where such terms have been discussed.</p>
```

2021-06-02 16:57 UTC, gkellogg approved these changes

2021-06-05 10:09 UTC, pchampin commented
This was discussed during yesterday's call: https://w3c.github.io/rdf-star/Minutes/2021-06-04.html#t05

2021-06-09 10:43 UTC, merged