Changes as per Issue #196
w3c/rdf-star pull request #210
Opened 2021-10-01 15:17 UTC by rdfguy

Explanatory paragraph added to the end of Section 2.1.

2021-10-01 15:35 UTC, gkellogg commented
For a future PR, better to use a branch other than "main", which would generally mirror the "main" branch of the target repo. That way, if there is some divergence, it doesn't mess up your fork.

2021-10-02 14:23 UTC, afs approved these changes

2021-10-02 14:26 UTC, afs commented
@rdfguy - the automatic IP check says "rdfguy is unknown, they need to link their GitHub account with a W3C account."

https://labs.w3.org/repo-manager/pr/id/w3c/rdf-star/210 

Would it be possible for you to add your GH account to your W3C account?

2021-10-03 14:40 UTC, gkellogg requested changes
This is useful, but, even though within a non-normative section, I think it makes more sense to enclose it in a Note.

2021-10-03 14:40 UTC, gkellogg commented on cg-spec/editors_draft.html
> +      <p>
<div class="note">
      <p>

2021-10-03 14:40 UTC, gkellogg commented on cg-spec/editors_draft.html
> +      </p>
</p>
      </div>

2021-10-04 15:38 UTC, hartig approved these changes
Fine now with the latest commit that encloses the text as a note.

2021-10-04 18:39 UTC, gkellogg approved these changes

2021-10-05 08:16 UTC, merged