Metadata
w3c/rdf-star pull request #217
Opened 2021-10-20 12:57 UTC by gatemezing

Replaced rdfs label by skos preflabels in other languages

2021-11-11 10:35 UTC, pchampin approved these changes
LGTM. I'm a little uncomfortable with the 'modified' date, which may get outdated if we don't update them manually... but I understand that there is some value in putting them there as well. We could possibly add script in the Makefile to update them automatically, but that should not defer the merging of this PR ;) https://xkcd.com/1319/

2021-11-11 21:05 UTC, gkellogg commented on tests/manifest.jsonld
> +            },
Sorry, I don't see that make-jsonld-manifests.rb has been modified in this PR.

2021-11-11 21:10 UTC, gkellogg commented on tests/trig/eval/manifest.ttl
> +   dct:creator [ foaf:homepage <https://w3c.github.io/rdf-star/> ; foaf:name " W3C RDF-star Working Group" ] ;
I don't see an entry for this in the manifest.jsonld version of the file, which should be created when the make-jsonld-manifests script is run.

2021-11-11 21:13 UTC, gkellogg requested changes
As mentioned in another comment, I don't see any changes to the make-jsonld-manifests.rb script to automate the update of the JSON-LD versions of the manifests. Running this script creates these files, and also ensures that the Turtle and JSON-LD versions of the files are isomorphic.

2021-11-12 06:40 UTC, pchampin commented
@gkellogg I missed that and you are right... all the more that the JSONLD and HTML versions of the trig/syntax and trig.eval manifest contain errors.

2021-11-12 06:44 UTC, pchampin commented
to be fair, the errors predate @gatemezing's PR, so I think we can merge the PR and fix this problem afterwards

2021-11-12 18:51 UTC, gkellogg commented
Very well, I'll take on the action to update the scripts once this is merged.

2021-11-12 18:51 UTC, gkellogg approved these changes

2021-11-13 22:02 UTC, gkellogg commented
I have changes staged for making both HTML and JSON-LD manifests once this PR is merged. Neither were building TriG manifests, but I've also made other changes to the HTML manifests.

2021-11-13 22:49 UTC, merged