adding morph-kgc implementation
w3c/rdf-star pull request #259
Opened 2022-04-27 12:40 UTC by dachafra

If this implementation isn't suitable for the webpage, please let us know where we can contribute with it :-)
Also closing `tr` and `td` tags in the table.

2022-04-27 14:04 UTC, TallTed requested changes
Implementations should be listed in alpha order.

(One more reason to make PRs focus on one change at a time....)

2022-04-27 14:04 UTC, TallTed commented on implementations.html
> +          </tr>
```suggestion
          </tr>
          <tr>
            <td>Morph-KGC</td>
            <td><a href="https://github.com/oeg-upm/morph-kgc">GitHub</a></td>
            <td><a href="https://w3id.org/kg-construct/rml-star">RML-star spec</a></td>
          </tr>
```

2022-04-27 14:04 UTC, TallTed commented on implementations.html
> +          </tr>
```suggestion
          </tr>
```

2022-04-27 14:04 UTC, TallTed commented on implementations.html
> +          </tr>
```suggestion
          </tr>
```

2022-04-27 14:04 UTC, TallTed commented on implementations.html
> +          </tr>
```suggestion
          </tr>
          <tr>
            <td>Apache Jena</td>
            <td>
              <a href="https://w3c.github.io/rdf-star/reports/#subj_Apache_Jena_">implementation report</a>,
              <a href="https://jena.apache.org/documentation/rdfstar/">documentation</a></td>
            <td></td>
          </tr>
```

2022-04-27 15:44 UTC, gkellogg commented
I agree with @afs; please add a commit which makes a minimal change to the original file, simply adding the new implementation without reformatting the existing code.

A separate PR can deal with any necessary reformatting or reordering of entries.

2022-04-28 07:54 UTC, dachafra commented
Done, and sorry for the noise

2022-04-28 08:10 UTC, pchampin approved these changes

2022-04-28 09:56 UTC, afs commented
Hi @dachafra - looks good as the combined effect.

Could you squash the PR to one commit for the change? The git history will look better.

It's showing up to me as all the changes, then the reverse, in 6 commits.

2022-04-28 10:23 UTC, pchampin commented
@afs github allows us to do this at merge time ("squash and merge"). This might be the easiest solution.
@dachafra note however that if we do that your 'main' branch will diverge from our 'main' branch... As a general advice for the future: always create dedicated branches for your pull requests to other repositories, and keep synced branches clean of any change on your side.

2022-04-28 10:25 UTC, afs commented
@pchampin yes, but.

It is clearer who the contributor is if the OP does the squash and force-pushes.

It's a detail to keep the history clean, not a blocker.

2022-04-28 11:48 UTC, closed without merging